# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "Magemaster 2000"
product_name = "Magemaster 2000"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "BigG_Corp"
chip = "rp2040"

[matrix]
matrix_type = "direct_pin"
direct_pin_low_active = true
direct_pins = [
    ["PIN_0", "PIN_1", "PIN_2", "PIN_3"],
    ["PIN_4", "PIN_5", "PIN_6", "PIN_9"],
]

[layout]
rows = 2
cols = 4
layers = 1
keymap = [
    [
        ["F4", "F7", "F10", "F2"],
        # nexturn toMain SkipStack confirm
        ["F11", "F5", "F9", "F3"],
        # PreEnd End TYT Cancel
    ]
]

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true



[storage]
# Storage feature is enabled by default
# enabled = false
